server:
  port: 7781
spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  jms:
    pub-sub-domain: true #flase queue   true topic

#自定义队列名
myTopic:  boot-activemq-topic


